steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/img-studio:latest',
        '--build-arg',
        '_PROJECT_ID=${_PROJECT_ID}',
        '--build-arg',
        '_VERTEX_API_LOCATION=${_VERTEX_API_LOCATION}',
        '--build-arg',
        '_GCS_BUCKET_LOCATION=${_GCS_BUCKET_LOCATION}',
        '--build-arg',
        '_GEMINI_MODEL=${_GEMINI_MODEL}',
        '--build-arg',
        '_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS=${_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS}',
        '--build-arg',
        '_NEXT_PUBLIC_OUTPUT_BUCKET=${_NEXT_PUBLIC_OUTPUT_BUCKET}',
        '--build-arg',
        '_NEXT_PUBLIC_TEAM_BUCKET=${_NEXT_PUBLIC_TEAM_BUCKET}',
        '--build-arg',
        '_NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI=${_NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI}',
        '.',
      ]
images:
  - 'gcr.io/$PROJECT_ID/img-studio:latest'

options:
  logging: CLOUD_LOGGING_ONLY
