steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'img-studio', # Replace with your desired image name
    '--build-arg',
    '_PROJECT_ID=${_PROJECT_ID}',
    '--build-arg',
    '_VERTEX_API_LOCATION=${_VERTEX_API_LOCATION}',
    '--build-arg',
    '_GCS_BUCKET_LOCATION=${_GCS_BUCKET_LOCATION}',
    '--build-arg',
    '_GEMINI_MODEL=${_GEMINI_MODEL}',
    '--build-arg',
    '_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS=${_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS}',
    '--build-arg',
    '_NEXT_PUBLIC_IMAGE_BUCKET_PREFIX=${_NEXT_PUBLIC_IMAGE_BUCKET_PREFIX}',
    '.'
  ]
